spring.application.name=DevSecOpsPlatform_Backend

server.port=8089
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/DevSecOpsPlatform?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
#Logging
logging.level.root = info
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} -%level -%logger{60} %msg %n
server.servlet.context-path=/projet

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
#jwt
app.secret-key=ee0c0ac2-e024-4bb4-a5b0-4296959c1e3d
app.expiration-time=90000