spring.application.name=DevSecOpsPlatform_Backend

server.port=8089

### DATABASE ###
spring.datasource.url=jdbc:postgresql://localhost:5432/EnviroTest
spring.datasource.username=postgres
spring.datasource.password=admin

### JPA / HIBERNATE ###
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.root=info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} -%level -%logger{60} %msg %n

server.servlet.context-path=/projet

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# jwt (expiration en ms : 86400000 = 24 h ; évite "utilisateur non connecté" après quelques minutes)
app.secret-key=ee0c0ac2-e024-4bb4-a5b0-4296959c1e3d
app.expiration-time=86400000

# --- Configuration GitLab ---
gitlab.url=https://gitlab.com
gitlab.api-url=https://gitlab.com/api/v4

gitlab.project-id=${GITLAB_PROJECT_ID:79441224}

# NE METS PAS LE VRAI TOKEN ICI. Configure-le dans IntelliJ ou ton OS.
gitlab.token=${GITLAB_TOKEN:CONFIGURED}
encryption.secret-key=${ENCRYPTION_SECRET_KEY:MySecretKey12345MySecretKey12345}

# Webhook GitLab (optionnel)
# Si tu définis un Secret token dans GitLab → mets la même valeur ici (idéalement via variable d'env)
gitlab.webhook.secret=${GITLAB_WEBHOOK_SECRET:CONFIGURED}

# --- Configuration Pipeline ---
# Ici on utilise ton chemin exact
pipeline.template-project=amanibennaceur-group/EnviroTest
pipeline.default-branch=master
pipeline.timeout-minutes=30


# sonar gloas-4ec46e8e3f9b9d185eabcad857d08fa22d981dfc30073b88b38b3fa3d2357cf2
# app id 4463805eeb503fb4b407004c716239c17f115debc903a446fae45ff10ae3d4a6
# personal access token glpat-8Ze4ZAHjUFdB2sf4_nrz2m86MQp1OmtsengzCw.01.121fke4yq
# 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
# enirotest-backend-token = glpat-MTPqE9SE27BPzl_DtOFbKW86MQp1OmtuOG1rCw.01.121605fud
# projet github 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